production:
  solr:
    hostname: 192.168.0.105
    port: 8983
    log_level: WARNING
    path: /solr/hsstat
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 192.168.0.105
    port: 8983
    log_level: INFO
    path: /solr/bvm

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/hsstat_test

